import { chromium } from "playwright";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const p = await b.newPage({ viewport: { width: 1600, height: 950 } });
await p.goto("http://localhost:4173");
await p.waitForTimeout(1400);
await p.getByText("Which facilities drive my A/R over 90 days?").first().click();
await p.waitForTimeout(1300);
await p.screenshot({ path: "/tmp/v2-chat.png" });
await p.getByRole("tab", { name: "Command Center" }).click();
await p.waitForTimeout(400);
await p.getByText("Chair Utilization", { exact: true }).first().click();
await p.waitForTimeout(500);
await p.screenshot({ path: "/tmp/v2-drill.png" });
await p.keyboard.press("Escape");
await p.getByRole("button", { name: "Recover variance" }).click();
await p.waitForTimeout(400);
await p.screenshot({ path: "/tmp/v2-agency.png" });
await p.getByRole("button", { name: /Confirm and submit/ }).click();
await p.waitForTimeout(600);
await p.screenshot({ path: "/tmp/v2-receipt.png" });
await b.close();
